### ISSUE TITLE
Bundle Products with dynamic pricing have price 0

### ISSUE THREAD

**Issue by davidverholen** [FACT-Finder-Web-Components/magento2-module#124]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 
1.1.0
- Magento edition and version: 
2.2.8 (should affect all, but the endless recursion bug - see below - was introduced in 2.2.7 or 2.2.8)
- PHP version: 
7.1.25
- Expected behavior: 
Bundles with dynamic pricing should have the price of the combined default selections
- Actual behavior: 
Bundles with dynamic pricing have the price 0
- Steps to reproduce: 
1. create some simple products with prices (for more "fun" add tier pricing and special prices)
2. create a bundle containing several simple products (marked as default) and set it to dynamic pricing

The bundle products should have the default selections applied for the "default" price calculation.
The Implementation below shows our current approach.

Be aware that since 2.2.7 or 2.2.8 there is a problem with an endless recursion on the getFinalPrice method of the bundle (I'm not 100% sure if it's generally the case or a project specific bug).
It might also have something to do with simple products not being in stock.

Example Implementation of Bundle Price Converter
```php
<?php
declare(strict_types=1);

namespace Brandung\Factfinder\Model\ProductExport\BundleConverter;

use Brandung\Factfinder\Model\FactfinderProduct;
use Brandung\Factfinder\Model\ProductExport\DefaultConverter\FieldDataConverterInterface;
use Magento\Bundle\Model\Product\Type;
use Magento\Catalog\Model\Product;
use Magento\Framework\Serialize\SerializerInterface;

class BundlePriceConverter implements FieldDataConverterInterface
{
    /**
     * @var SerializerInterface
     */
    private $serializer;

    public function __construct(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }

    /**
     * @param Product $product
     * @param string[] $targetFieldData
     * @return string[]
     */
    public function convert(Product $product, array $targetFieldData): array
    {
        $usedSelections = [];
        foreach ($this->getDefaultSelections($product) as $selectionId => $defaultSelection) {
            $selectionId = $defaultSelection->getData('selection_id');
            $usedSelections[$selectionId] = $selectionId;
            $product->addCustomOption('selection_qty_' . $selectionId, $defaultSelection->getData('selection_qty'));
        }
        $product->addCustomOption('bundle_selection_ids', $this->serializer->serialize($usedSelections));
        $targetFieldData[FactfinderProduct::PRICE] = round($product->getFinalPrice(), 2);
        return $targetFieldData;
    }

    /**
     * @param Product $product
     * @return Product[]
     */
    private function getDefaultSelections(Product $product): array
    {
        /** @var Type $typeInstance */
        $typeInstance = $product->getTypeInstance();
        $selections = $typeInstance->getSelectionsCollection($typeInstance->getOptionsIds($product), $product);
        /** @var Product[] $defaultSelections */
        return array_filter($selections->getItems(), function (Product $productSelection) {
            return (bool)$productSelection->getData('is_default') === true;
        });
    }
}
```

**Comment by a-laurowski** [comment]
Hi @davidverholen
Thanks for the report and detailed description. We'll investigate that issue

**Comment by fmarangi** [comment]
Hi @davidverholen, we implemented the "composite" (bundle and grouped) product export in the current `develop`, we would appreciate your input on this.

**Comment by davidverholen** [comment]
@fmarangi with bundled products there could still be the "problem" (might depend on business needs) that a bundle product by default has no selections (even if "default" for the selection(s) is checked) and so the price is 0.

Did not test it yet though

**Comment by a-laurowski** [comment]
hi @davidverholen 
We've changed implementation. Now the lowest price of all selection for bundle product will be be exported if none of options are required
