### ISSUE TITLE
search does not work on pages with multiple fragments in its path

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#138]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 1.1.2
- Magento edition and version: CE 2.2.8
- PHP version: 7.1.25
- Expected behavior: when doing a search, the extension should always navigate to the search result page (`/FACT-Finder/result`)
- Actual behavior: when doing a search on a page, that contains multiple path fragments, the wrong URL will be requested for the FACT-Finder result page
- Steps to reproduce: open any page in your Magento shop that contains multiple path fragments, e.g. a subcategory page like `example.org/vegetables-and-fruits/fruits.html`. Then on that page, enter a search query into the FACT-Finder search box. It will redirect you to `example.org/vegetables-and-fruits/FACT-Finder/result` instead of `example.org/FACT-Finder/result`

Another example: doing a search on a page with an URL like `example.org/custom/route/` will redirect you to `example.org/custom/route/FACT-Finder/result`.

**Comment by a-laurowski** [comment]
Hi @fritzmg 
Unfortunately I was not able to reproduce behaviour, You described.
Could You please add breakpoints in lines pointed in links below and paste the value of variable baseUrl?

https://github.com/FACT-Finder-Web-Components/magento2-module/blob/3c4bf57e63d116e197faa68513600b009fa91856/src/view/frontend/web/js/search-navigation.js#L7

https://github.com/magento/magento2/blob/c3f29ce8efa1e59c7e1f01b6eab2f09504442924/lib/web/mage/url.js#L23

In my situation, at http://magento2.3.local/men/tops-men/hoodies-and-sweatshirts-men.html the baseUrl was http://magento2.3.local

**Comment by fritzmg** [comment]
On the URL https://example.org/obst-gemuse/obst.html the variable `redirectPath` in https://github.com/FACT-Finder-Web-Components/magento2-module/blob/3c4bf57e63d116e197faa68513600b009fa91856/src/view/frontend/web/js/search-navigation.js#L7 is `"FACT-Finder/result"` and the variable `baseUrl` in https://github.com/magento/magento2/blob/c3f29ce8efa1e59c7e1f01b6eab2f09504442924/lib/web/mage/url.js#L23 is `""` (empty).

**Comment by fritzmg** [comment]
`setBaseUrl` of url.js is apparently never called. Only the global `BASE_URL` variable exists.

**Comment by a-laurowski** [comment]
I've debbuged `setBaseUrl ` method and it's first call is from 
https://github.com/magento/magento2/blob/0c786907ffe03d0e2990612eec16ee58b00379c5/app/code/Magento/Customer/view/frontend/web/js/view/authentication-popup.js#L38

which is triggered right after page is loaded. Perhaps You have this component disabled. Of course disabling this component, shouldn't affect FACT-Finder module. We'll add setting `setBaseUrl` before this line:
https://github.com/FACT-Finder-Web-Components/magento2-module/blob/3c4bf57e63d116e197faa68513600b009fa91856/src/view/frontend/web/js/search-navigation.js#L7

**Comment by fritzmg** [comment]
Yeah, as far as I can see the Magento core does not set the base URL automatically for the URL builder - which makes sense, because you might want to build an URL with a different base URL.
