### ISSUE TITLE
Magento 2.2 currently not supported

### ISSUE THREAD

**Issue by davidverholen** [FACT-Finder-Web-Components/magento2-module#159]
While the Readme states that the Module is compatible with >= 2.2, it is currently not installable with 2.2

- FACT-Finder-Web-Components Magento2-Module version (see composer.json): latest 
- Magento edition and version: 2.2.9
- PHP version: 7.1

- Expected behavior: 
Module should be installable with 2.2.9
- Actual behavior: 
Composer Restriction forbids installing with 2.2.9
- Steps to reproduce: 
Install Magento 2.2.9
Try to install factfinder magento2 integration via composer

minimum version for Magento_Directory is  100.3.0 while Magento 2.2.9 is on 100.2.8
See: https://github.com/magento/magento2/blob/2.2.9/composer.json#L131

Or is there a specific reason why this Directory Version is not supported?

**Comment by a-laurowski** [comment]
Hi @davidverholen and thanks for reporting this.
The module should be compatible with magento 2.2. In this case "magento/directory" module version provided in composer.json will be changed to previous, used in Magento 2.2 if only it's compatible

**Comment by a-laurowski** [comment]
hi @davidverholen, version of module/directory was changed to 100.2.0 and merged in https://github.com/FACT-Finder-Web-Components/magento2-module/pull/160.
