### ISSUE TITLE
Documentation - improve export section

### ISSUE THREAD

**Issue by carstenklaus** [FACT-Finder-Web-Components/magento2-module#178]
It is not immediately obvious that there are several variants - Pull (FTP export) and Push (Http export). Especially when scrolling down the page, it is easy to overlook "Http Export". 

In addition, the "Cron configuration" should not be listed under "Http Export", since the setting is made directly in FACT-Finder. This should also be explained shortly.

**Comment by toarm** [comment]
@a-laurowski @fmarangi 
Can someone please take a look and chagne the documentation accordingly.

**Comment by a-laurowski** [comment]
@toarm Sure, I'm working on that

**Comment by a-laurowski** [comment]
I'm closing this ticket - Documentation is updated and merged to develop.
