### ISSUE TITLE
Integrate with Slick Slider

### ISSUE THREAD

**Issue by avstudnitz** [FACT-Finder-Web-Components/magento2-module#181]
I want to display a record list with a slick slider which is already integrated in the project. My code looks as follows:

```
<ff-record-list class="product-slider" data-pagination-prefix="<?= __('Page') ?>" unresolved>
    <ff-record itemprop="itemListElement" itemscope="">
        <div class="product-tile" data-bind="scope: 'product-tile'" data-container="product-grid" id="product-item-{{record.Master}}"> ...</div>
    </ff-record>
</ff-record-list>
```

Unfortunately, the slick slider sets the width to 0px which makes the result look odd. I assume that the slick slider is initialized before the product tiles are rendered. I tried a few variants, but with no success.
Is there an approach which allows to trigger a JS event (for initializing Slick Slider) AFTER rendering the product tiles?

**Comment by toarm** [comment]
Hi @avstudnitz ,
yes there is. All components which are capable of rendering content are firing an event called `dom-updated`. It's exactly what you are looking for. 

Please find our ff-record-list-3d demo which is utilizing jQuery 3d Hover plugin and `dom-updated` event: 
https://github.com/FACT-Finder-Web-Components/demos/blob/release/3.x/ff-record-list-3d/index.html

**Comment by avstudnitz** [comment]
Great, thank you!
