### ISSUE TITLE
Access multi attribute value in record list

### ISSUE THREAD

**Issue by avstudnitz** [FACT-Finder-Web-Components/magento2-module#183]
How can I access a value of a multi attribute field from a record list? I have the value indexed with `|Key1=Value1|Key2=Value2|Key3=Value3|` and set the field to type "Multi-Attribute" in the Fact-Finder configuration. How can I access it? 
I tried `record.FieldName.Key1`, but with no success.

**Comment by fmarangi** [comment]
Hi @avstudnitz, please have a look here https://web-components.fact-finder.de/api/3.x/ff-middleware#tab=docs

**Comment by avstudnitz** [comment]
Thanks!
