### ISSUE TITLE
Can't add new Field into CSV

### ISSUE THREAD

**Issue by pravalitera** [FACT-Finder-Web-Components/magento2-module#185]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 1.3.2
- Magento edition and version: 2.3.3
- PHP version: 7.2
- Expected behavior: Add datas to the .csv export
- Actual behavior: no data added
- Steps to reproduce: Just follow your own instructions in this very github

I checked in _Omikron\Factfinder\Model\Export\Catalog\ProductType\SimpleDataProvider_ , the data is in the array returned by the _toArray_ function, but the data is not in the CSV

**Comment by fmarangi** [comment]
Hi @pravalitera, did you also name your new field in the export feed DI declaration?

    <virtualType name="Omikron\Factfinder\Model\Export\CatalogFeed">
        <arguments>
            <argument name="columns" xsi:type="array">
                <item name="MyNewField" xsi:type="string">MyNewField</item>
            </argument>
        </arguments>
    </virtualType>

**Comment by pravalitera** [comment]
Indeed, it works 👍 

You should change the doc, because the _virtualType_ you are talking about, is in the "_Changing existing column names_" section. That's why i did not try it :)

Thx !

**Comment by fmarangi** [comment]
I know, sorry about it. There is a PR open with changes on the README file, we'll make sure to add this too. Thanks for point it out!
