### ISSUE TITLE
Can't export product data to FTP

### ISSUE THREAD

**Issue by michi-p** [FACT-Finder-Web-Components/magento2-module#23]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 
0.1.0 (release v0.9-beta.2)

- Magento edition and version: 
Magento CE 2.2.4

- PHP version: 
7.1.13

- Expected behavior: 
  * FACT Finder export function is executed and saves generated files on ftp server

- Actual behavior: 
  * FACT Finder export function is executed throws an exception 
```Can't connect to FTP!```
when trying to upload the generated files

- Steps to reproduce: 
  * configure FACT Finder FTP access data in Magento backend
  * execute FACT Finder export function (e.g. via CLI command)

- Additional information
  * if you comment line 84 in Omikron\Factfinder\Helper\Upload 
```// $this->ftp->write($destinationPath, $content); ``` 
no exception is thrown

**Comment by jaroslawweselski** [comment]
Hello,

Do you use Windows? In the module we are calling `open()` function which uses `ftp_ssl_connect() `function. 

After debugging we found out that the error was:

> Call to undefined function ftp_ssl_connect

Solution for that is:

> Note: Why this function may not exist
> ftp_ssl_connect() is only available if both the ftp module and the OpenSSL support is built statically into php, this means that on Windows this function will be undefined in the official PHP builds. To make this function available on Windows you must compile your own PHP binaries.

Reference: http://www.php.net/manual/en/function.ftp-ssl-connect.php

Can you check what hapeens when you remove `@` in Magento files (`vendor\magento\framework\Filesystem\Io\Ftp.php` - line 110). That would give us confirmation, if this error occurs also on your side.

**Comment by michi-p** [comment]
Hello,

the server is running on Debian 8.10.

>  Can you check what hapeens when you remove @ in Magento files (vendor\magento\framework\Filesystem\Io\Ftp.php - line 110). That would give us confirmation, if this error occurs also on your side.

Now I get following error 
```
Warning: ftp_fput(): php_connect_nonb() failed: Operation now in progress (115) in /home/devshkbj/www.devshop.kastner.at/webshop/vendor/magento/framework/Filesystem/Io/Ftp.php on line 261
```

**Comment by jaroslawweselski** [comment]
Hello,

Does your FTP server require other port than 21?

**Comment by michi-p** [comment]
The passive ports of the FTP connection were blocked on our server. It's working now - thank you.
