### ISSUE TITLE
Info about broken image-URLs if the root of Magento is in the /pub-folder

### ISSUE THREAD

**Issue by TimPietrusky** [FACT-Finder-Web-Components/magento2-module#251]
In #74 we can find information on what needs to be done if the URLs in the FactFinder-Export are broken as they contain the `/pub` in the URL. It would be nice to have a short info/reference to that issue in the README so that it's more obvious what a Magento-User has to do if they follow the guidelines of Magento.

**Comment by a-laurowski** [comment]
Hi @TimPietrusky 
Thanks for reporting that. We will add proper information in the README file.

**Comment by TimPietrusky** [comment]
@a-laurowski thank you very much!

**Comment by a-laurowski** [comment]
Hi @TimPietrusky 
We've added new section `Troubleshooting` to README file.
First entry is related to the unwanted `pub/` fragment in exported URL.
Feel free to report any other issue which might be worthy of putting on that section.

**Comment by TimPietrusky** [comment]
@a-laurowski thank you very much! To be 100 % correct I would replace `env.php` with `config.php`, as the `config.php` goes into the project-repo, the `env.php` just stays on the server as it contains the database-credentials. But of course this can be decided by everyone ;)
