### ISSUE TITLE
Exported CSV doesn't contain any products, only the header-row

### ISSUE THREAD

**Issue by TimPietrusky** [FACT-Finder-Web-Components/magento2-module#253]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 1.6.1
- Magento edition and version: 2.3.2

## Expected behavior
When I execute `bin/magento factfinder:export:products` on the server, the exported CSV-file contains all my products.

## Actual behavior
The exported file only contains the header-row, but nothing else:
```
ProductNumber;Master;Name;Description;Short;ProductURL;Price;Brand;Availability;MagentoId;ImageURL;CategoryPath;Attributes;HasVariants
```

There is also no log in `var/log/factfinder.log` even when this is activated in the backend. I also don't see the message `Store $storeId: File $path has been generated.` after the export is done. Also there are no files for the other storeViews. 

## Steps to reproduce
I have actually no idea, it worked in one Magento 2.3.2 installation, it doesn't work in the other. I can't seem to find the problem, everything is configured the same in the FactFinder extension. Products are enabled & assigned to categories. 

What needs to be fulfilled so that a product is inside the exported CSV?

**Comment by TimPietrusky** [comment]
The only thing I can imagine right now is to deactivate all modules one by one and see if that makes a difference. I just wonder why I see no debug stuff in any log, even when the `developer`-mode is activated.

**Comment by fmarangi** [comment]
Hi @TimPietrusky and thank you for your feedback! TBH, it is the first time something like this is reported, and it looks strange at first glance.

From your description, I assume no error occurs during the export process, which is fine. You can verify this with `echo $?`, which gives you the exit status of the last run command. If there was no error, the export is indeed successful. In this case, the first thing I would check is the product collection (src/Model/Export/Catalog/Products.php). Maybe try to insert some `var_dump` there, or use a debugger, to check if and how many products are loaded. Let us know your findings!

**Comment by TimPietrusky** [comment]
@fmarangi When I execute `echo $?` I can see `255` which looks like there is an error, as I would expect to see `0` if there is no error. Or what do you think? 

I will try to debug the code as you suggested.

**Comment by TimPietrusky** [comment]
@fmarangi I can see that there are 3200 products loaded from the database, trying to work my way up in the chain to see where it fails to actually use these products.

**Comment by TimPietrusky** [comment]
It seems that src/Model/Export/Catalog/ProductType/SimpleDataProvider.php#toArray() is triggering the problem when it tries to get the `Brand`: 

```
'Brand'         => (string) $this->product->getAttributeText('manufacturer')
```

This will call `vendor/magento/module-catalog/Model/Product.php#getAttributeText` and results in a fatal error, as the attribute `manufacturer` doesn't exist:

```
28-Jul-2020 12:35:45 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getSource() on bool in /home/purasstg/magento2/releases/40/vendor/magento/module-catalog/Model/Product.php:1826
Stack trace:
#0 /home/purasstg/magento2/releases/40/generated/code/Magento/Catalog/Model/Product/Interceptor.php(1090): Magento\Catalog\Model\Product->getAttributeText('manufacturer')
#1 /home/purasstg/magento2/releases/40/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/SimpleDataProvider.php(60): Magento\Catalog\Model\Product\Interceptor->getAttributeText('manufacturer')
#2 /home/purasstg/magento2/releases/40/vendor/omikron/magento2-factfinder/src/Model/Exporter.php(26): Omikron\Factfinder\Model\Export\Catalog\ProductType\SimpleDataProvider->toArray()
#3 /home/purasstg/magento2/releases/40/vendor/omikron/magento2-factfinder/src/Model/Export/Feed.php(32): Omikron\Factfinder\Model\Exporter->exportEntities(Object(Omikron\Factfinder\Model\Stream\Csv), Object(Omikron\Factfinder\Model\Export\Catalog\DataProvider), Array)
#4 /home/purasstg/ in /home/purasstg/magento2/releases/40/vendor/magento/module-catalog/Model/Product.php on line 1826
```

So I guess in that other installation someone deleted the attribute and the export fails silently.

**Comment by fmarangi** [comment]
`manufacturer` is actually installed per default in Magento, see https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/ConfigurableProduct/Setup/Patch/Data/InstallInitialConfigurableAttributes.php#L55, that's why it is done like that.

**Comment by TimPietrusky** [comment]
@fmarangi yeah that is true, but you can delete it without any problem in Magento if you don't need it. So in theory it would be nice if your module would check if that attribute actually exists and log an error into `factfinder.log` instead of failing silently. I understand that this is an edge case, but a case nevertheless.

**Comment by fmarangi** [comment]
@TimPietrusky want to do a Pull Request for it?

**Comment by TimPietrusky** [comment]
@fmarangi how would you like to get this solved? Check for every attribute that could be deleted if it is there? And then raise an exception or try to log into the `factfinder.log`? Or do you have a better idea?

**Comment by fmarangi** [comment]
The current implementation results in a fatal error. I would move it to a custom field (https://github.com/FACT-Finder-Web-Components/magento2-module/blob/master/src/Api/Export/Catalog/ProductFieldInterface.php), and implement some additional logic there. It is important that we raise an exception (which is catchable) instead of a fatal error.

**Comment by TimPietrusky** [comment]
Yeah then someone else has to take over, as I'm not a PHP nor a Magento dev, I just know enough to debug a problem.

**Comment by fmarangi** [comment]
@TimPietrusky fyi

**Comment by TimPietrusky** [comment]
@fmarangi thank you very much!
