### ISSUE TITLE
Attribute export

### ISSUE THREAD

**Issue by fmarangi** [FACT-Finder-Web-Components/magento2-module#260]
Custom Magento attributes should be exported:

* in a dedicated field
* in a multiattribute field
* in a multiattribute field, containing only numerical values

Such a feed structure allows an easy and effective management in FACT-Finder. In order to obtain such a structure, we need to refactor the feed generation and its configuration in the admin panel.

**Comment by mikeg-de** [comment]
@a-laurowski / @fmarangi what about searchable_attributes containing only the attribute values?

**Comment by fmarangi** [comment]
@mikeg-de where would this data come from? Afaik there is nothing like that in a standard Magento installation. It would be really a cool feature indeed, but we cannot offer a common approach for all projects - unless we install a dedicated attribute for it, but some customers might not want that. In case, we could add a readme note regarding this.

If you have an idea regarding this, we'll be certainly happy about your contribution!

**Comment by mikeg-de** [comment]
It like the filterable but w/o the attribute names. Like it is available in the flagbit module for M1.

**Comment by fmarangi** [comment]
We have implemented and merged this feature, would be cool to get feedback on this @mikeg-de !
