### ISSUE TITLE
Not compatible with CSP (Content Security Policy)

### ISSUE THREAD

**Issue by simonrl** [FACT-Finder-Web-Components/magento2-module#272]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): **^1.5, required by NG module**
- Magento edition and version: **Commerce 2.3.5**
- PHP version: **7.2**
- Expected behavior: Usage of the extension does not log CSP errors to the browser's dev console
- Actual behavior: CSP errors are logged to the browser's dev console:
```
[Report Only] Refused to connect to 'https://ng-demo.fact-finder.de/fact-finder/rest/v3/campaign/<customer>/product?sid=<..>&productNumber=<..>&format=json' because it violates the following Content Security Policy directive: "connect-src geostag.cardinalcommerce.com geo.cardinalcommerce.com 1eafstag.cardinalcommerce.com 1eaf.cardinalcommerce.com centinelapistag.cardinalcommerce.com centinelapi.cardinalcommerce.com 'self' 'unsafe-inline'".
```

- Steps to reproduce: Install module, configure it and open a product that has recommendations or simply search something

**Further info:**
Externally loaded resources should be whitelisted.
This is explained here:
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/security/content-security-policies.html
When we enable CSP for production, the current state of the module will stop working. Of course we can add a custom module where we whitelist the sources, but imho the FF module should take care of that.

**Comment by a-laurowski** [comment]
Hi @simonrl  and thanks for reporting that.
We already added CSP whitelist to to future release compatible with Magento 2.4
https://github.com/FACT-Finder-Web-Components/magento2-module/pull/269/files?file-filters%5B%5D=.xml#diff-df9dae74080cbb12e0cc78eb138207c4 
but apparently we have to apply the same change to the current version

**Comment by simonrl** [comment]
Hi @a-laurowski ,

thanks a lot for the swift reply.

Do you have a ETA when this will be applied to the current version?

Thanks
Simon

**Comment by a-laurowski** [comment]
Hi @simonrl 
New release including CSP module compatibility has been released
https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v1.6.3

**Comment by simonrl** [comment]
Nice, thanks.
