### ISSUE TITLE
Tried to resize the image in my theme but its not working

### ISSUE THREAD

**Issue by anaraniwal** [FACT-Finder-Web-Components/magento2-module#275]
I tried to rewrite the etc/view.xml file and i have put the size 500 * 500 but its still showing me 200 * 200.

**Comment by fmarangi** [comment]
Hi @anaraniwal! I just tried to reproduce your issue on a dev instance (CE 2.4) and entering a different size in the `etc/view.xml` - everything works as expected. Do you mind posting your code here, so that I can have a look?

**Comment by fmarangi** [comment]
Hey @anaraniwal any updates on this?
