### ISSUE TITLE
Triggering a search does not redirect to search page anymore

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#342]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 1.7.0
- Magento edition and version: 2.3.7 CE
- PHP version: 7.4

**Expected behavior:**

Triggering a search with 

```js
factfinder.communication.EventAggregator.addFFEvent({
    type: 'search',
    query: '…'
});
```

automatically redirects to search result page.

**Actual behavior:**

Triggering a search with 

```js
factfinder.communication.EventAggregator.addFFEvent({
    type: 'search',
    query: '…'
});
```

does not automatically redirect to search result page.

**Description:**

Up until version `1.5.1` triggering a search with

```js
factfinder.communication.EventAggregator.addFFEvent({
    type: 'search',
    query: '…'
});
```

also automatically caused a redirect to the search result page, becuase the FACT-Finder Magento Extension registered a callback this way:

https://github.com/FACT-Finder-Web-Components/magento2-module/blob/v1.5.1/src/view/frontend/web/js/search-navigation.js

However, now it is only event listener on the `.search-wrapper` element:

https://github.com/FACT-Finder-Web-Components/magento2-module/blob/v1.7.0/src/view/frontend/web/js/search-redirect.js

Meaning that it only works when a search is triggered from within the `ff-searchbox` web component (though I could not figure out where this `before-search` event is actually triggered). But in our case we have some custom JavaScript where we would like to trigger searches in other ways, which we have done with `factfinder.communication.EventAggregator.addFFEvent`.

As far as I can see, the behaviour would also be the same in version `2.1.0`.

Or is there a new, better way to trigger a search via JavaScript (which would also automatically redirect to the search result page)?

**Comment by a-laurowski** [comment]
Hi @fritzmg ant thanks for reporting that.
We switched to `before-search` listener to narrow the actions we are interfering with only to search requests issued bye the searchbox so I think you've been using the side effect we wanted to eliminate.

Would introducing an utility like `searchAndRedirect` in module be good for you? We would rather not change the current implementation as with it it's easier to detect when redirection should takes place, and as we initially want, we are not interfere we each request just like we did with the `addBeforeDispatchingCallback`.

**Comment by fritzmg** [comment]
> Would introducing an utility like `searchAndRedirect` in module be good for you?

That would be sufficient for us. We only need to rigger a search with a specific search term (and any parameters currently already defined) - which would automatically redirect to the search result page, if not already on there.

**Comment by a-laurowski** [comment]
Hi @fritzmg 
We just release a new version with this functionality
https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v2.2.0
