### ISSUE TITLE
$_SERVER can be insecure

### ISSUE THREAD

**Issue by bjoern-flagbit** [FACT-Finder-Web-Components/magento2-module#4]
**See**
https://github.com/FACT-Finder-Web-Components/magento2-module/blob/d5987890aec11b984f7879be226613ec86b16ab5/Omikron/Factfinder/Controller/Adminhtml/Export/Feed.php#L58

The question is why we need this here? I'm pretty sure you can do this with the request interface in magento2.

**Comment by bjoern-flagbit** [comment]
Let's just ignore this and close the issue is a very good idea. 🙈

**Comment by jaroslawweselski** [comment]
I propose first to look what is actually merged...

**Comment by bjoern-flagbit** [comment]
I did :) But only on master ;) So good job 👍
