### ISSUE TITLE
Magento 2.4.4

### ISSUE THREAD

**Issue by Fulmenef** [FACT-Finder-Web-Components/magento2-module#408]
Hi,
The version v4.0.0 seems to include the upgrade from php 7.3 to 7.4, but it's not compatible with Magento 2.4.4 which require php 8.1. Are there plans to make this upgrade ?

**Comment by a-laurowski** [comment]
hi @Fulmenef 
 
Sure we are planning to provide a module version that will use all 8.1 features but on the other hand we still need to support current customers who are still stay on older versions of Magento2 and use older php versions. This is unfortunately a hard process.

The[ composer.json](https://github.com/magento/magento2/blob/2.4.4/composer.json#L20) in magento repository says that 7.4 should becompatible. Can you provide an output of `composer install` to show me what exactly causes installation to fail?

disclaimer:  v4. i still just a release candidate. There is no official release from that branch

**Comment by Fulmenef** [comment]
Thanks for your feedback @a-laurowski.
As you said, the composer.json still allow 7.4 (although the [documentation](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) doesn't mention it). However PHP 7.4 will no longer be supported in 6 months (as per the [calendar](https://www.php.net/supported-versions.php)) so we are trying to upgrade our project as soon as possible.
So because we are using PHP 8.1, the module is incompatible.

**Comment by a-laurowski** [comment]
hi @Fulmenef  we will sort this out.
Perhaps declaring compatibility with PHP versions 8.1 will be good enough. I don't know a full list of syntax of things that have been removed in 8.0 (if any) so we will need to test the module against that version on Magento 2.4.4. I will keep you updated

**Comment by a-laurowski** [comment]
hi @Fulmenef
The last release candidate of version 4 should be compatible with 2.4.4
https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v4.0.0-rc.3

**Comment by simonrl** [comment]
I'd like to bring some attention to this question again.

2.4.5 is only compatible with PHP 8.1.
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html?mt=false

So we basically need a working release of this module to proceed with out Magento upgrade.

Thanks

**Comment by grzegorz-jamroz** [comment]
Hi @simonrl 

We are supporting PHP 8.1 from version `v3.6.0` https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v3.6.0

As always we encourage to install the most recent one.

Thanks
