### ISSUE TITLE
Custom parameters should be add to requests

### ISSUE THREAD

**Issue by michi-p** [FACT-Finder-Web-Components/magento2-module#42]
The parameter `add-params` should be added to each request (not only search) e.g. SimilarRecords.ff, Recommender.ff, ...

**Comment by toarm** [comment]
Currently `add-params` is only supposed to appear on search request. 
We introduced a similar attribute for tracking params `add-tracking-params`.

To keep this appraoch we would have to implement something like `add-recommendation-params`. 

Guess thats a feature request for https://github.com/FACT-Finder-Web-Components/ff-web-components

**Comment by fritzmg** [comment]
In our case we need the parameters in every FF request. We are not sure how this can be done.

**Comment by toarm** [comment]
https://web-components.fact-finder.de/api/core-event-aggregator#tab=docs -> Hooking into the pipeline
`addBeforeDispatchingCallback(fn)` is what you are looking for

**Comment by toarm** [comment]
feel free to reopen if you have any questions
