### ISSUE TITLE
DI compilation has failed on module v4.0.0-rc.4

### ISSUE THREAD

**Issue by Citizen4our** [FACT-Finder-Web-Components/magento2-module#435]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json):  v4.0.0-rc.4
- Magento edition and version: Magento 2.4.5,
- PHP version: 8.1
run  `php bin/magento s:d:c`

- Expected behavior: 
Generated code and dependency injection configuration successfully.
- Actual behavior: 
3 errors 
<img width="1733" alt="image" src="https://user-images.githubusercontent.com/47303372/216005573-4b9add11-cee7-4cbe-a557-93c702da3866.png">

- Steps to reproduce: 
just run  `php bin/magento s:d:c`

**Comment by Citizen4our** [comment]
attached composer patch:
 [fix_di_compile_errors.patch](https://github.com/FACT-Finder-Web-Components/magento2-module/files/10555495/fix_di_compile_errors.patch)

**Comment by grzegorz-jamroz** [comment]
Hi @Citizen4our , thank you for you reporting. We will handle it soon.

**Comment by grzegorz-jamroz** [comment]
Hi @Citizen4our solution has been added https://github.com/FACT-Finder-Web-Components/magento2-module/commit/9a42d4a31fff09db30a3f7f245a992f5df439011

Next release will embrace this fix.

**Comment by grzegorz-jamroz** [comment]
Hi @Citizen4our,

new release is avaliable https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v4.0.1 - it contains fix :) 

Please let me know if problem disappear for you.

**Comment by Citizen4our** [comment]
Hi,
Thanks, looks good.
