### ISSUE TITLE
Cannot push data via SFTP because of SecLib 3

### ISSUE THREAD

**Issue by amenk** [FACT-Finder-Web-Components/magento2-module#441]
- FACT-Finder-Web-Components Magento2-Module version (see composer.lock):  4.1.0
- Magento edition and version: 2.4.5-p1
- PHP version: 8.1
- Expected behavior: We can push the datafeed via SFTP via key auth
- Actual behavior: 
```
[2023-03-09T12:44:58.096988+00:00] .CRITICAL: Error: Class "phpseclib\Net\SFTP" not found in /var/www/html/project/web/vendor/omikron/magento2-factfinder/src/Model/Filesystem/Io/SftpPublicKeyAuth.php:29
```
- Steps to reproduce: 
* Define a SFTP key
* Try to upload
* Push the test connection button
* A 500 server error appears in the admin panel
* The above error is logged

- Additional info

We actually have seclib 3 which is a requirement of Magento:

```
$ composer why phpseclib/phpseclib
magento/magento2-base             2.4.5-p1 requires phpseclib/phpseclib (~3.0.13)         
magento/product-community-edition 2.4.5-p1 requires phpseclib/phpseclib (~3.0.13)         
php-amqplib/php-amqplib           v3.2.0   requires phpseclib/phpseclib (^2.0|^3.0)       
phpseclib/mcrypt_compat           2.0.3    requires phpseclib/phpseclib (>=3.0.13 <4.0.0) 
```

phpseclib 3 uses the seclib 3 namespace: https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SFTP.php#L36

Maybe it's enough to just change the namespace.

**Comment by grzegorz-jamroz** [comment]
Hi @amenk thank you for your reporting. We will handle it soon.

**Comment by amenk** [comment]
@grzegorz-jamroz is this a bigger thing? Would be great if this can be fixed very soon ;-)

**Comment by grzegorz-jamroz** [comment]
Hi @amenk new release https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v4.1.1 is ready :) 

It contains fix for your problem :)

Thank you for your engagement :)
