### ISSUE TITLE
Attribute values are always null in feed with attributes that contain a number in the code

### ISSUE THREAD

**Issue by DanieliMi** [FACT-Finder-Web-Components/magento2-module#443]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): v4.1.0
- Magento edition and version: 2.4.5-p1
- PHP version: 8.1
- Expected behavior: Attribute value is added to the feed.
- Actual behavior: The field is always `null`.
- Steps to reproduce:
  1. Create an attribute with the code "p2m_topseller" as boolean
  2. Set it to true to one product
  3. Generate a product feed

The problem lies in `\Omikron\Factfinder\Model\Export\Catalog\AttributeValuesExtractor::getAttributeValues`  here `\Magento\Framework\DataObject::getDataUsingMethod` is used. It seems to be a limitation of Magento that it can correctly generate the method for the attribute (getP2mTopseller) but `\Magento\Framework\DataObject::_underscore` cannot correctly convert it back into the attribute code (p_2m_topseller).

This could be resolved if using `getData`. Do you have any reason for using `getDataUsingMethod` specifically?

**Comment by grzegorz-jamroz** [comment]
Hi @DanieliMi thank you for you reporting. We will handle it soon.

**Comment by grzegorz-jamroz** [comment]
Hi @DanieliMi we have added solution to branch https://github.com/FACT-Finder-Web-Components/magento2-module/commit/cd755acd8ea2b0c1507fd109b48d8c6f11e51be0 which solves problem.

It will be released in next release.

Thank you for your engagement :)

**Comment by DanieliMi** [comment]
Hi @grzegorz-jamroz thank you for the fix! I just testet it with the release/4.x branch and it works. Do you have an ETA on when this fix will be released?

Is there any chance #439 will be merged?

**Comment by grzegorz-jamroz** [comment]
Hi @DanieliMi sorry we missed this - yes it could be and we merged it 👍

**Comment by Rayn93** [comment]
Hi @DanieliMi.
New release: https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v4.1.2 is ready. It contains your requested changes. 
Thank you for your cooperation.
