### ISSUE TITLE
FFWEB-697 - add support for CMS export

### ISSUE THREAD

**Issue by toarm** [FACT-Finder-Web-Components/magento2-module#45]
We have several customers which also use FACT-Finder as their CMS search.
To do so, we need the data from Magento.
Pleas add a function which allows the customer to export the CMS data, similar to Magento 1.

Magento2 has a new CMS System in the Enterprise Edition, we also have to look into this.
https://www.bluefootcms.com/

**Comment by a-laurowski** [comment]
Released in 1.0.0
