### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by DanieliMi** [FACT-Finder-Web-Components/magento2-module#456]
Magento 2.4.6 supports PHP 8.2 . Is there a chance you could Support PHP 8.2?

**Comment by Rayn93** [comment]
Hi @DanieliMi 
If you need just export features for Fact-Finder, we prepared a special export SDK for Magento2 which supports PHP 8.2
Now FactFinder team verify this new SDK if everything works fine. Probably in September, it will be ready to use.

For WebC SDK we have the plan to prepare a new major version of SDK which will include support for PHP 8.2. Unfortunately, SDK v5.x will be ready later (end of 2023).

**Comment by DanieliMi** [comment]
Hi @Rayn93 , thank you for the information. We indeed only need the export functionality. I am looking forward to the SDK!

I think for now we will be using 2.4.6 with 8.1 until the SDK is available and we can switch to that.

**Comment by Rayn93** [comment]
Great. I will update you when the export SDK will be ready.

**Comment by DanieliMi** [comment]
Awesome, thank you!

**Comment by Rayn93** [comment]
Hi @DanieliMi 
Our new export SDK which support PHP 8.2 is already released. 
https://github.com/FACT-Finder/magento2-export-module

**Comment by DanieliMi** [comment]
Hi @Rayn93, cool thank you very much for the info!
