### ISSUE TITLE
Issues with stock items in 5.x

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#503]
Version 5.0.0 is missing critical fixes regarding the export, specifically for handling the stock items. These fixes are missing in 5.x:

* https://github.com/FACT-Finder-Web-Components/magento2-module/commit/d8bc14dae9e4711b881fecc8a679303fd2557387
* https://github.com/FACT-Finder-Web-Components/magento2-module/commit/9c537dfe4eae88a94ece1882fd73058bac04a858

**Comment by Rayn93** [comment]
Hi @fritzmg 
Yes, you are right. Thanks for notice it. We will prepare changes for v5.x too.

**Comment by Rayn93** [comment]
@fritzmg 
Support for MSI was add: https://github.com/FACT-Finder-Web-Components/magento2-module/pull/507
It should be released next week.
Thank you for your cooperation.
