### ISSUE TITLE
FFWEB-919/why is there a PRODUCT_LIMIT?

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#52]
The `Omikron\Factfinder\Model\Export\Product` class [defines a PRODUCT_LIMIT](https://github.com/FACT-Finder-Web-Components/magento2-module/blob/v0.9-beta.5/Omikron/Factfinder/Model/Export/Product.php#L17) of 50000 which is then used in the [`buildFeed`](https://github.com/FACT-Finder-Web-Components/magento2-module/blob/v0.9-beta.5/Omikron/Factfinder/Model/Export/Product.php#L265-L297) method. It is implemented in such a way that at most 50000 products will be exported to FACT Finder. If your store has 60000 products, those last 10000 will be ignored.

What is the limit for? Obviously we would like to export _all_ products to FACT Finder, not just the first 50000.

**Comment by toarm** [comment]
Hi @fritzmg ,
50.000 is the limit of characters per record. This is actually a FACT-Finder limitation and mentioned in the export data documentation.

However this limit shouldn't  be applied to the number of products.

**Comment by fritzmg** [comment]
I see, then the current implementation is simply incorrect.

**Comment by a-laurowski** [comment]
I've created an internal ticket and will work on this issue

**Comment by fritzmg** [comment]
I have already made some changes and will provide them as a PR as soon as I have figured out the problems caused by https://github.com/FACT-Finder-Web-Components/magento2-module/pull/46

**Comment by a-laurowski** [comment]
@fritzmg 
I've already create a pull request :)
Also added a product batching , because script can exhaust allowed memory while loading a larger collections. 
I consider this product limit was originally created as some kind of solution for memory exhaustion issues.

**Comment by a-laurowski** [comment]
The newest version 0.9-beta.6 of module have this limit removed.

**Comment by a-laurowski** [comment]
Hi @fritzmg . The newest version 0.9-beta.6 of module have this limit removed.
